-- =============================================================================
-- Migration V1: Baseline schema
-- Project : eventslk / event-registration-api
-- Date    : 2026-07-13
-- =============================================================================
-- Full schema baseline generated from the Hibernate-managed dev database
-- (consolidates the former manual V2 seat/image script, which was never run
-- through Flyway). From this point on, ddl-auto stays on "validate" and every
-- schema change ships as a new V<n>__*.sql file.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------
CREATE TABLE user_entity (
    user_id                       BIGINT       NOT NULL,
    username                      VARCHAR(255),
    email                         VARCHAR(255),
    password                      VARCHAR(255),
    role                          VARCHAR(255),
    email_verified                BOOLEAN      NOT NULL,
    email_verified_at             TIMESTAMP(6) WITH TIME ZONE,
    verification_token            VARCHAR(64),
    verification_token_expires_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT user_entity_pkey       PRIMARY KEY (user_id),
    CONSTRAINT user_entity_email_key  UNIQUE (email),
    CONSTRAINT user_entity_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- Hibernate pooled ID generator; INCREMENT 50 must match the entity's
-- allocationSize — do not change one without the other.
CREATE SEQUENCE user_entity_seq START WITH 1 INCREMENT BY 50;

-- ---------------------------------------------------------------------------
-- Events
-- ---------------------------------------------------------------------------
CREATE TABLE event_entity (
    event_id        VARCHAR(255)  NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    location        VARCHAR(255),
    image_url       VARCHAR(1024),
    -- Java-serialized ArrayList<LocalDateTime> (legacy mapping); migrate to a
    -- proper collection table in a future migration if querying by date is needed.
    dates           BYTEA,
    total_seats     INTEGER       NOT NULL,
    available_seats INTEGER       NOT NULL,
    -- Optimistic lock version; managed by JPA @Version — never update manually.
    version         INTEGER       NOT NULL,
    CONSTRAINT event_entity_pkey PRIMARY KEY (event_id)
);

CREATE TABLE event_price_ranges (
    event_id VARCHAR(255) NOT NULL,
    label    VARCHAR(255),
    price    DOUBLE PRECISION,
    CONSTRAINT fk_price_ranges_event FOREIGN KEY (event_id) REFERENCES event_entity (event_id)
);

-- ---------------------------------------------------------------------------
-- Bookings
-- ---------------------------------------------------------------------------
CREATE TABLE booking_order_entity (
    booking_id    VARCHAR(255) NOT NULL,
    event_id      VARCHAR(255),
    user_id       BIGINT,
    ticket_number VARCHAR(255),
    order_status  VARCHAR(255),
    ordered_date  TIMESTAMP(6) WITHOUT TIME ZONE,
    seat_count    INTEGER      NOT NULL,
    CONSTRAINT booking_order_entity_pkey PRIMARY KEY (booking_id)
);

-- ---------------------------------------------------------------------------
-- Transactional outbox (relayed to Kafka by OutboxPoller)
-- ---------------------------------------------------------------------------
CREATE TABLE outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    payload        TEXT         NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT outbox_event_pkey PRIMARY KEY (id),
    CONSTRAINT outbox_event_status_check CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED'))
);

-- ---------------------------------------------------------------------------
-- Performance indexes
-- ---------------------------------------------------------------------------
-- Outbox poller scans by status ordered by age.
CREATE INDEX idx_outbox_status_created ON outbox_event (status, created_at);

-- Seat-availability checks during concurrent booking bursts.
CREATE INDEX idx_event_available_seats ON event_entity (available_seats);

-- Cancellation lookups by user + status.
CREATE INDEX idx_booking_user_status ON booking_order_entity (user_id, order_status);
